Fixes #3456 - Add aria-labelled-by attributes to wizard step icons
webcompat/webcompat.com pull request #3516
Opened 2021-01-17 20:56 UTC by miketaylr

In theory this should fix #3456, but the devtools accessbility inspector doesn't recognize the `aria-labelled-by` attribute, but I think that's a bug (I will file one and post a link here).

![Screen Shot 2021-01-17 at 2 52 17 PM](https://user-images.githubusercontent.com/67283/104855709-e5b32a00-58d3-11eb-9136-af850f540105.png)

We can fix this error by duplicating the description text, but then a screen reader will read it twice, which seems bad. 
![Screen Shot 2021-01-17 at 2 51 40 PM](https://user-images.githubusercontent.com/67283/104855710-e64bc080-58d3-11eb-9a1a-8da25169b49e.png)

2021-01-17 21:03 UTC, miketaylr commented
https://bugzilla.mozilla.org/show_bug.cgi?id=1687198

2021-01-18 17:02 UTC, ksy36 commented on webcompat/templates/nav/issue-wizard-stepper.html
> +                <div aria-labelled-by="step-label-{{ step.id }}" role="img" class="icon"></div>
```suggestion
                <div aria-labelledby="step-label-{{ step.id }}" role="img" class="icon"></div>
```

2021-01-18 17:03 UTC, ksy36 requested changes
Thanks for looking into this! Not very familiar with this property, so I looked it up, looks like like it's `aria-labelledby=""` (without the hyphen), so may be devtools not recognizing it because of the hyphen

2021-01-19 14:43 UTC, miketaylr commented
> Thanks for looking into this! Not very familiar with this property, so I looked it up, looks like like it's `aria-labelledby=""` (without the hyphen), so may be devtools not recognizing it because of the hyphen

Oh yay, thanks for the careful review!

2021-01-19 15:27 UTC, miketaylr commented
Nice, just confirmed it works :)

![Screen Shot 2021-01-19 at 9 27 16 AM](https://user-images.githubusercontent.com/67283/105055334-933f4e00-5a38-11eb-9710-18492f1622ca.png)

2021-01-19 15:29 UTC, miketaylr commented
I guess we can do the same thing with the other icons, so let's not merge this just yet @ksy36 -- I can add that maybe later tonight.

![Screen Shot 2021-01-19 at 9 29 16 AM](https://user-images.githubusercontent.com/67283/105055644-e4e7d880-5a38-11eb-97f3-a5bbc9f1cf01.png)

2021-01-20 01:43 UTC, miketaylr commented
Oh wait, those messages are about interactive semantics, etc. I don't plan on addressing those. We got all the image label issues taken care of.
<img width="420" alt="Screen Shot 2021-01-19 at 7 43 34 PM" src="https://user-images.githubusercontent.com/67283/105115559-a41aae80-5a8e-11eb-855f-20e63bd57127.png">


r? @ksy36

2021-01-20 02:07 UTC, karlcow commented
Thanks!

2021-01-20 15:48 UTC, ksy36 approved these changes
Cool, thanks!

2021-01-20 15:48 UTC, merged

2021-01-20 17:32 UTC, miketaylr commented
Thanks all!